# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- highlightrecovery

pool:
  vmImage: "vs2017-win2016"

variables:
  MSYS2_ROOT: $(System.Workfolder)\msys64
  MSYS_PAC: $(System.Workfolder)\msys64\usr\bin\pacman.exe
  MSYS_BASH: $(System.Workfolder)\msys64\usr\bin\bash.exe

steps:
  - script: |
      choco install msys2 --params="/InstallDir:%MSYS2_ROOT% /NoUpdate /NoPath"
    displayName: Install MSYS2
  - script: |
      %MSYS_PAC% --noconfirm --Syyuu
      %MSYS_PAC% --noconfirm --needed -S ^
      tar gzip nano make diffutils intltool git ^
      mingw-w64-x86_64-{gcc,gdb,make,pkg-config,cmake} ^
      mingw-w64-x86_64-{lcms2,libtiff,exiv2,libjpeg-turbo,libraw,qt5,qtwebkit}
    displayName: Install Dependencies
  - script: |
      mkdir librt
      cd librt
      git clone https://github.com/CarVac/librtprocess lrt
      echo "done clone"
      mkdir buildDir
      cd buildDir
      echo "starting build script"
      set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;%MSYS2_ROOT%\mingw64\bin;%MSYS2_ROOT%\usr\bin
      set HOME=.
      %MSYS_BASH% -lc "echo $PWD"
      echo "after first bash call"
      %MSYS_BASH% -lc "../../azure_build_librt.sh > out.log 2>err.log"
    displayName: build librtprocess
    timeoutInMinutes: 5
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'librt/buildDir' 
      artifactName: 'filmulator_built_folder_error'
  - script: |
      mkdir build
      pushd build
      mkdir installed
      set INSTALLDIR=installed
      set HOME=.
      %MSYS_BASH% -c "cmake -G\"MSYS Makefiles\" -DCMAKE_BUILD_TYPE=\"$BUILD_TYPE\"-DCMAKE_INSTALL_PREFIX=$INSTALLDIR ../filmulator-gui >output.log 2>err.log"
      %MSYS_BASH% -c "make -j4"
      %MSYS_BASH% -c "make install"
      popd
    displayName: build filmulator
  - script: |
      listdll="libbz2-1.dll
        libdouble-conversion.dll
        libexiv2.dll
        libexpat-1.dll
        libfreetype-6.dl
        libgcc_s_seh-1.dll
        libglib-2.0-0.dll
        libgomp-1.dlll
        libgraphite2.dll
        libharfbuzz-0.dll
        libiconv-2.dll
        libicudt*.dll
        libicuin*.dll
        libicuuc*.dll
        libintl-8.dll
        libjasper-4.dll
        libjpeg-8.dll
        liblcms2-2.dll
        liblzma-5.dll
        libpcre-1.dll
        libpcre2-16-0.dll
        libpng16-16.dll
        libraw_r-*.dll
        librtprocess.dll
        libstdc++-6.dll
        libtiff-5.dll
        libwinpthread-1.dll
        libzstd.dll
        zlib1.dll"
      find build/
      cp $MSYS2_ROOT/MINGW64/bin/{$listdll} build/installed/bin/
      cd build/installed/bin
      $MSYS_BASH -lc "/usr/bin/windeployqt.exe --release --qmldir qml/filmulator-gui filmulator.exe"
    displayName: package dlls
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'build/installed' 
      artifactName: 'filmulator_built_folder' 